name: actions-mvp-pull
on: [push]
jobs:
        build:
                runs-on: windows-latest
                name: Python sample
                steps:
                        - uses: actions/checkout@v2
                        - name: Setting up Python  
                          uses: actions/setup-python@v2
                          with:
                                  python-version: '3.7'
                                  architecture: 'x64'
                        - name: Install dependencies
                          run: |
                                  python -m pip install --upgrade pip
                                  pip install -r requirements.txt
                        - name: Run script
                          run: python main.py
                        - name: Print Name
                          run: echo "My name is Peter"
