name: actions-mvp-pull
on: [push]
jobs:
        build:
                runs-on: windows-latest
                name: Python '3.9' sample
                steps:
                        - uses: actions/checkout@v2
                        - name: Setting up Python  
                          uses: actions/setup-python@v2
                          with:
                                  python-version: '3.9'
                                  architecture: 'x64'
                        - run: python main.py
